services:
  nginx:
    image: nginx:latest
    container_name: ${CONTAINER_NAME}
    restart: always
    ports:
      - "80"
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge
