services:
  nginx:
    image: nginx:latest
    container_name: ${CONTAINER_NAME}
    restart: always
    network_mode: "${NETWORK_MODE:-bridge}"
    ports:
      - "80"
    networks:
      - nginx-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  nginx-network:
    driver: bridge
