services:
  db:
    container_name: postgres_sysbench_template
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    image: postgres