services:
  db:
    env_file:
      - .env
    environment:
      - ACCEPT_EULA=${ACCEPT_EULA}
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=${MSSQL_PID}
      - MSSQL_AGENT_ENABLED=${MSSQL_AGENT_ENABLED}
    ports:
      - ${MSSQL_PORT}:1433
    image: mcr.microsoft.com/mssql/server:2022-CU15-ubuntu-22.04
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets