services:
  db:
    container_name: postgres_sysbench_template
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - PGDATA=/pgdata
    ports:
      - "5432"
    volumes:
      - ./data:/pgdata
    image: postgres