services:
  db:
    container_name: postgres_sysbench_template
    network_mode: "${NETWORK_MODE:-bridge}"
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - PGDATA=/pgdata
    ports:
      - "5432"
    volumes:
      - ./data:/pgdata
    tmpfs:
      - /var/lib/postgresql
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s