services:
  redis:
    image: redis:7-alpine
    container_name: ${CONTAINER_NAME}
    restart: always
    network_mode: "${NETWORK_MODE:-bridge}"
    command: redis-server --requirepass ${REDIS_PASSWORD} --maxmemory ${REDIS_MAXMEMORY} --maxmemory-policy ${REDIS_MAXMEMORY_POLICY}
    ports:
      - "6379"
    volumes:
      - ./data:/data
    networks:
      - redis-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  redis-network:
    driver: bridge