services:
  prometheus:
    image: prom/prometheus:latest
    container_name: ${CONTAINER_NAME}-prometheus
    restart: always
    network_mode: "${NETWORK_MODE:-bridge}"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --web.enable-lifecycle
      - --storage.tsdb.retention.time=${PROMETHEUS_RETENTION}
    ports:
      - "9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/data:/prometheus
    healthcheck:
      test: ["CMD-SHELL", "wget --spider --quiet http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - monitoring-network

  grafana:
    image: grafana/grafana:latest
    container_name: ${CONTAINER_NAME}-grafana
    restart: always
    network_mode: "${NETWORK_MODE:-bridge}"
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      GF_USERS_ALLOW_SIGN_UP: ${GRAFANA_ALLOW_SIGN_UP}
      GF_INSTALL_PLUGINS: ${GRAFANA_PLUGINS}
    ports:
      - "3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - monitoring-network
    depends_on:
      prometheus:
        condition: service_healthy

  node-exporter:
    image: prom/node-exporter:latest
    container_name: ${CONTAINER_NAME}-node-exporter
    restart: always
    network_mode: "${NETWORK_MODE:-bridge}"
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --path.rootfs=/host
      - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)
    ports:
      - "9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host:ro
    healthcheck:
      test: ["CMD-SHELL", "wget --spider --quiet http://localhost:9100/"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 15s
    networks:
      - monitoring-network

networks:
  monitoring-network:
    driver: bridge