services:
  arangodb:
    image: arangodb:3.11
    container_name: ${CONTAINER_NAME}
    restart: always
    environment:
      ARANGO_ROOT_PASSWORD: ${ARANGO_ROOT_PASSWORD}
      ARANGODB_OVERRIDE_DETECTED_TOTAL_MEMORY: ${ARANGODB_OVERRIDE_DETECTED_TOTAL_MEMORY:-}
      ARANGODB_OVERRIDE_DETECTED_NUMBER_OF_CORES: ${ARANGODB_OVERRIDE_DETECTED_NUMBER_OF_CORES:-}
    ports:
      - "8529"
    volumes:
      - ./data:/var/lib/arangodb3
      - ./apps:/var/lib/arangodb3-apps
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:8529/_api/version || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - arangodb-network

networks:
  arangodb-network:
    driver: bridge
