services:
  elasticsearch:
    image: elasticsearch:8.11.0
    container_name: ${CONTAINER_NAME}
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=${ES_SECURITY_ENABLED}
      - "ES_JAVA_OPTS=-Xms${ES_HEAP_SIZE} -Xmx${ES_HEAP_SIZE}"
      - cluster.name=${ES_CLUSTER_NAME}
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - ${ES_PORT}:9200
      - ${ES_TRANSPORT_PORT}:9300
    volumes:
      - ./data:/usr/share/elasticsearch/data
    networks:
      - elastic-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  kibana:
    image: kibana:8.11.0
    container_name: ${CONTAINER_NAME}-kibana
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - SERVER_NAME=${KIBANA_SERVER_NAME}
      - SERVER_HOST=0.0.0.0
    ports:
      - ${KIBANA_PORT}:5601
    networks:
      - elastic-network
    depends_on:
      - elasticsearch
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5601/api/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  elastic-network:
    driver: bridge