services:
  db:
    image: mariadb:10.3
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306"
    volumes:
      - ./data/mariadb:/var/lib/mysql
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin
    restart: always
    env_file:
      - .env
    ports:
      - "80"
    environment:
      PMA_ARBITRARY: ${PMA_ARBITRARY}
      PMA_HOST: ${PMA_HOST}
      PMA_PORT: ${PMA_PORT}
    depends_on:
      - db
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge