services:
  db:
    network_mode: "${NETWORK_MODE:-bridge}"
    env_file:
      - .env
    environment:
      - ACCEPT_EULA=${ACCEPT_EULA}
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=${MSSQL_PID}
      - MSSQL_AGENT_ENABLED=${MSSQL_AGENT_ENABLED}
    ports:
      - "1433"
    image: mcr.microsoft.com/mssql/server:2022-CU15-ubuntu-22.04
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P $${MSSQL_SA_PASSWORD} -C -Q 'SELECT 1' -b -o /dev/null"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 60s