#!/bin/bash

# === Renet Compose Support ===
_use_renet() {
  [[ -n "$REPOSITORY_NETWORK_ID" ]] && command -v renet &>/dev/null
}
_compose() {
  if _use_renet; then
    renet compose --network-id "$REPOSITORY_NETWORK_ID" -- "$@"
  else
    docker compose "$@"
  fi
}

prep() {
  docker pull mcr.microsoft.com/mssql/server:2022-CU15-ubuntu-22.04
  mkdir -p  data  log  secrets
  chmod 777 data/ log/ secrets/

  return $?
}

up() {
  _compose up -d

  return $?
}

down() {
  _compose down -v

  return $?
}
