services:
  neo4j:
    image: neo4j:5-community
    container_name: ${CONTAINER_NAME}
    restart: always
    network_mode: "${NETWORK_MODE:-bridge}"
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH}
      - NEO4J_PLUGINS=${NEO4J_PLUGINS}
      - NEO4J_server_memory_heap_initial__size=${NEO4J_server_memory_heap_initial__size}
      - NEO4J_server_memory_heap_max__size=${NEO4J_server_memory_heap_max__size}
      - NEO4J_server_memory_pagecache_size=${NEO4J_server_memory_pagecache_size}
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
    ports:
      - "7474"  # Neo4j Browser (HTTP)
      - "7687"  # Bolt protocol
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./conf:/conf
      - ./plugins:/plugins
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
