#!/bin/bash

prep() {
    echo "Pulling MongoDB image..."
    docker pull mongo:7.0
    docker pull mongo-express:latest
    
    echo "Creating data directory..."
    mkdir -p ./data
    chmod 755 ./data
    
    return $?
}

up() {
    if [ -f .env ]; then
        source .env
    fi
    
    echo "Starting MongoDB server..."
    docker compose up -d
    return $?
}

down() {
    echo "Stopping MongoDB server..."
    docker compose down -v
    return $?
}

