services:
  orientdb:
    image: orientdb:3.2
    container_name: ${CONTAINER_NAME}
    restart: always
    environment:
      ORIENTDB_ROOT_PASSWORD: ${ORIENTDB_ROOT_PASSWORD}
    ports:
      - "2424"  # Binary protocol
      - "2480"  # HTTP/REST API and Studio
    volumes:
      - ./databases:/orientdb/databases
      - ./backup:/orientdb/backup
      - ./config:/orientdb/config
    networks:
      - orientdb-network

networks:
  orientdb-network:
    driver: bridge
