services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: ${CONTAINER_NAME}
    restart: always
    ports:
      - "9000"
      - "9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    healthcheck:
      test: ["CMD-SHELL", "timeout 5 sh -c '</dev/tcp/localhost/9000' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    networks:
      - portainer-network

networks:
  portainer-network:
    driver: bridge
