services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: ${CONTAINER_NAME}
    restart: always
    ports:
      - "9000"
      - "9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - portainer-network

networks:
  portainer-network:
    driver: bridge
