services:
  elasticsearch:
    image: elasticsearch:8.11.0
    container_name: ${CONTAINER_NAME}
    restart: always
    network_mode: "${NETWORK_MODE:-bridge}"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=${ES_SECURITY_ENABLED}
      - "ES_JAVA_OPTS=-Xms${ES_HEAP_SIZE} -Xmx${ES_HEAP_SIZE}"
      - cluster.name=${ES_CLUSTER_NAME}
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200"
      - "9300"
    volumes:
      - ./data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:9200/_cluster/health | grep -E 'green|yellow' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  kibana:
    image: kibana:8.11.0
    container_name: ${CONTAINER_NAME}-kibana
    restart: always
    network_mode: "${NETWORK_MODE:-bridge}"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - SERVER_NAME=${KIBANA_SERVER_NAME}
      - SERVER_HOST=0.0.0.0
    ports:
      - "5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:5601/api/status | grep -q available || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s